### ISSUE TITLE
.NET SDK

### ISSUE THREAD

**Issue by ryanhlewis** [Walrusking16/Appwrite-Unity-SDK#1]
Hey Walrusking16,

I saw this repo recommended to me, and I remember doing similar work with Unity Appwrite in the past.
You don't need to make a whole new SDK for it- there's already support. It's labelled "dotnet", although, it is C# and works 
within Unity completely. All you need to do is import and use these CS files. 

Here's their official server SDK: https://github.com/appwrite/sdk-for-dotnet

Awhile back, I used AppWrite in Unity too, and instead of doing in-line REST, I opted to quickly build out a client SDK,
since they only provide a Server SDK. Here's my working client SDK: https://github.com/ryanhlewis/sdk-for-dotnet
It may be a few versions old now, but it looks like they haven't made any drastic changes, so it'll probably still work.

It's really only changes to the one file difference between the Server SDK and the Client SDK: Account.cs
https://github.com/appwrite/sdk-for-dotnet/pull/10/commits/d6f8ff1cba0a8299d795b65ac106322553a75491

The reason there is no official client SDK for DotNet is because they want to use their generator for all the SDKs. 
See https://github.com/appwrite/sdk-for-dotnet/pull/10

Just wanted to let you know!

**Comment by Walrusking16** [comment]
Hey thanks for the information. I am just working on this for fun, and building it with unity's methods to communicate with api's. I don't currently have any plans to use appwrite in unity as I only really need it for my websites, but I also do game development so this seemed like a neat project to work on that incorporated both. I will keep the repo's you mentioned in mind if that changes. Thanks!
